
server:
  port: 8092

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gid
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: kafka, edu.miu.speedservice.dto.SensorRecordDto
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  main:
    allow-bean-definition-overriding: true
app:
  topic:
    tofasttopic: tofasttopic
    ownertopic: ownertopic
logging:
  level:
    root: INFO



