logging:
  level:
    root: INFO
    org.springframework.: INFO

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  zipkin:
    base-url: http://localhost:9411/
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)

