logging:
  level:
    root: INFO
    org.springframework.: INFO

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  zipkin:
    base-url: http://localhost:9411/
sleuth:
  sampler:
    probability: 1 #100% (default = 10%)

