server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.: INFO

zuul:
  routes:
    product-service:
      path: /product/**
      serviceId: WebShopComponentsProducts
      stripPrefix: true
#      url: http://localhost:8091
    customer:
      serviceId: WebShopComponentsCustomers
#      url: http://localhost:8092
    cart:
      serviceId: WebShopComponentsShopping
#      url: http://localhost:8093
    order:
      serviceId: WebShopComponentsOrder
#      url: http://localhost:8094

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

product-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    listOfServers: https://example1.com,http://example2.com
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100

spring:
  zipkin:
    base-url: http://localhost:9411/
sleuth:
  sampler:
    probability: 1 #100% (default = 10%)

