spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb

logging:
  level:
    root: INFO
    org.springframework.: INFO

server:
  port: 8094

customersURL: http://localhost:8092
productsURL: http://localhost:8091

spring.activemq.broker-url: tcp://localhost:61616
spring.activemq.user: admin
spring.activemq.password: admin