server:
  port: 8094

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

logging:
  level:
    root: INFO
    org.springframework.: INFO

customersURL: http://localhost:8092
productsURL: http://localhost:8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
