spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb

logging:
  level:
    root: ERROR
    org.springframework.: ERROR

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
