mongodb:
  primary:
    host: localhost
    port: 27017
    database: productdb
  secondary:
    host: localhost
    port: 27017
    database: shoppingcartdb

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration