server:
  port: 8092
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
      clientId: theClient
      client-secret: thisissecret
    resource:
      user-info-uri: http://localhost:8080/user

